RestarauntWebApp/Models/DishDTO.cs
using RestarauntWebApp.Domain.Entities;
using System.ComponentModel.DataAnnotations;

namespace RestarauntWebApp.Models
{
    public class DishDTO
    {
        public int? Id { get; set; }
        public int? Weight { get; set; }
        public int? Price { get; set; }
        public string? CategoryName { get; set; }
        public IEnumerable<ToppingDTO>? ToppingsDTO { get; set; }
        public string? Name { get; set; }
        public string? Description { get; set; }
        public string? PhotoFileName { get; set; }
    }

    public class ToppingDTO
    {
        public int? Id { get; set; }
        public string? Name { get; set; }
        public int? Price { get; set; }
    }
}

RestarauntWebApp/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace RestarauntWebApp.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Логин")]
        public string? UserName { get; set; }

        [Required]
        [UIHint("password")]
        [Display(Name = "Пароль")]
        public string? Password { get; set; }

        [Display(Name = "Запомнить меня")]
        public bool RememberMe { get; set; }
    }
}

RestarauntWebApp/Controllers/AccountController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RestarauntWebApp.Models;
using SignInResult = Microsoft.AspNetCore.Identity.SignInResult;

namespace RestarauntWebApp.Controllers
{
    public class AccountController : Controller
    {
        private readonly SignInManager<IdentityUser> _signInManager;

        public AccountController(SignInManager<IdentityUser> signInManager)
        {
            _signInManager = signInManager;
        }

        [HttpGet]
        public async Task<IActionResult> Login(string? returnUrl)
        {
            //Завершаемый текущий сеанс
            await _signInManager.SignOutAsync();

            ViewBag.ReturnUrl = returnUrl;

            return View(new LoginViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model, string? returnUrl)
        {
            //Раздел сайта (URL), куда перенаправить пользователя после успешного логина
            ViewBag.ReturnUrl = returnUrl;

            if (!ModelState.IsValid)
                return View(model);
            SignInResult result = await _signInManager.PasswordSignInAsync(model.UserName!, model.Password!, model.RememberMe, false);

            if (result.Succeeded)
            {
                return Redirect(returnUrl ?? "/");
            }

            ModelState.AddModelError(string.Empty, "Неверный логин или пароль");
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

RestarauntWebApp/Controllers/DishesController.cs
using Microsoft.AspNetCore.Mvc;
using RestarauntWebApp.Domain;
using RestarauntWebApp.Domain.Entities;
using RestarauntWebApp.Infrastructure;
using RestarauntWebApp.Models;

namespace RestarauntWebApp.Controllers
{
    public class DishesController : Controller
    {
        private readonly DataManager _dataManager;

        public DishesController(DataManager dataManager)
        {
            _dataManager = dataManager;
        }

        public async Task<IActionResult> Index()
        {
            return View(HelperDTO.TransformDishes(await _dataManager.Dishes.GetDishesAsync(), _dataManager));
        }

        public async Task<IActionResult> Show(int id)
        {
            Dish? entity = await _dataManager.Dishes.GetDishByIdAsync(id);

            if (entity is null) return NotFound();

            return View(HelperDTO.TransformDish(entity, _dataManager));
        }
    }
}

RestarauntWebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace RestarauntWebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Contacts()
        {
            return View();
        }
    }
}

RestarauntWebApp/Controllers/ServicesController.cs
using Microsoft.AspNetCore.Mvc;
using RestarauntWebApp.Domain;
using RestarauntWebApp.Domain.Entities;
using RestarauntWebApp.Infrastructure;
using RestarauntWebApp.Models;

namespace RestarauntWebApp.Controllers
{
    public class ServicesController : Controller
    {
        private readonly DataManager _dataManager;

        public ServicesController(DataManager dataManager)
        {
            _dataManager = dataManager;
        }

        public async Task<IActionResult> Index()
        {
            return View(HelperDTO.TransformServices(await _dataManager.Services.GetServicesAsync()));
        }

        public async Task<IActionResult> Show(int id)
        {
            Service? entity = await _dataManager.Services.GetServiceByIdAsync(id);

            if (entity is null) return NotFound();

            return View(HelperDTO.TransformService(entity));
        }
    }
}

RestarauntWebApp/Views/Admin/DishCategoriesEdit.cshtml
@model DishCategory
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<div>
    <h2>
        @strTitle
    </h2>
    <div>
        <form asp-area="" asp-controller="Admin" asp-action="DishCategoriesEdit" method="post">
            <input type="hidden" asp-for="Id"/>
            
            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="@Model.Name"></label>
                <input asp-for="@Model.Name" />
                <span asp-validation-for="@Model.Name"></span>
            </div>
            
            <input type="submit" value="Сохранить"/>
        </form>
    </div>
</div>

RestarauntWebApp/Views/Admin/DishesEdit.cshtml
@model Dish
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<style>
    button{
        color: #000 !important;
    }
</style>

<script src="https://cdn.tiny.cloud/1/mb85kxtsc4oiknkstnihv9iqf01r1cw1d0w597fvsj47bk6a/tinymce/8/tinymce.min.js" referrerpolicy="origin" crossorigin="anonymous"></script>

<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="" asp-controller="Admin" asp-action="DishesEdit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id"/>
            <input type="hidden" asp-for="Photo"/>
            
            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <select asp-for="DishCategoryId">
                    <option value="">Выберите из списка...</option>
                    @foreach (DishCategory entity in ViewBag.DishCategories)
                    {
                        <option value="@entity.Id">@entity.Name</option>
                    }
                </select>
                <span asp-validation-for="DishCategoryId"></span>
            </div>
            <div class="div-box">
                <label asp-for="Name"></label>
                <input asp-for="Name" />
                <span asp-validation-for="Name"></span>
            </div>
            <div class="div-box">
                <label asp-for="Price"></label>
                <input asp-for="Price">
                <span asp-validation-for="Price"></span>
            </div>
            <div class="div-box">
                <label asp-for="Weight"></label>
                <input asp-for="Weight">
                <span asp-validation-for="Weight"></span>
            </div>
            <div class="div-box">
                <label asp-for="Description"></label>
                <textarea asp-for="Description"></textarea>
                <span asp-validation-for="Description"></span>
            </div>
            <div class="div-box">
                <label asp-for="Photo"></label>
                <input type="file" name="titleImageFile" id="titleImageFile"/>
                <div>
                    <img class="img-block" src="~/img/@Model.Photo"/>
                </div>
            </div>
            <div class="div-box">
                <select multiple="multiple" asp-for="ToppingsIds">
                    <option value="-1">Выберите из списка...</option>
                    @foreach (Topping entity in ViewBag.Toppings)
                    {
                        <option value="@entity.Id" id="option-@entity.Id">
                            @entity.Name
                        </option>
                    }
                </select>
            </div>
            <input type="submit" value="Сохранить"/>
        </form>
    </div>
</div>
<script>
    tinymce.init({
      selector: 'textarea',
      language: 'ru',
      onboarding: false,
      plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount',
      toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link media table mergetags | addcomment showcomments | spellcheckdialog a11ycheck typography uploadcare | align lineheight | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
      automatic_uploads: true,
      images_upload_url: '/admin/SaveEditorImg',
      images_reuse_filename: false,
      image_dimensions: false,
      paste_data_images: true,
      convert_urls: false
    });
</script>

RestarauntWebApp/Views/Admin/Index.cshtml
@{
    string strTitle = "Панель администратора";
    ViewBag.Title = strTitle;
    IEnumerable<DishCategory>? dishCategories = ViewBag.DishCategories;
    IEnumerable<Dish>? dishes = ViewBag.Dishes;
    IEnumerable<Topping>? toppings = ViewBag.Toppings;
}

<div>
    <h2>@strTitle</h2>
    <div>
        <h3>Категории блюд</h3>
        <div class="div-box">
            <a asp-area="" asp-controller="Admin" asp-action="DishCategoriesEdit" asp-route-id="">Добавить категорию блюд</a>
        </div>
        @if (dishCategories.Any())
        {
            <div>
                @foreach (var entity in dishCategories)
                {
                    <div>
                        <span>
                            @($"{entity.Name}")
                        </span>
                        |
                        <a asp-area="" asp-controller="Admin" asp-action="DishCategoriesEdit" asp-route-id="@entity.Id">Редактировать</a>
                        |
                        <form style="display: inline-block;" id="form-category-@entity.Id" asp-area=""
                              asp-controller="Admin" asp-action="DishCategoriesDelete" method="post">
                            <input type="hidden" name="id" value="@entity.Id"/>
                            <a href="#" onclick="document.getElementById('form-category-@entity.Id').submit();">Удалить</a>
                        </form>

                    </div>
                }
            </div>
        }
    </div>
    <div>
        <h3>Меню</h3>
        <div class="div-box">
            <a asp-area="" asp-controller="Admin" asp-action="DishesEdit" asp-route-id="">Добавить блюдо</a>
        </div>
        @if (dishes.Any())
        {
            <div>
                @foreach (var entity in dishes)
                {
                    <div>
                        <span>
                            <a asp-area="" asp-controller="Dishes" asp-action="Show" asp-route-id="@entity.Id">
                                @($"{entity.Name}")
                            </a>
                            |
                            @($"{entity.DishCategory?.Name}") 
                        </span>
                        |
                        <a asp-area="" asp-controller="Admin" asp-action="DishesEdit" asp-route-id="@entity.Id">Редактировать</a>
                        |
                        <form style="display: inline-block;" id="form-@entity.Id" asp-area=""
                              asp-controller="Admin" asp-action="DishesDelete" method="post">
                            <input type="hidden" name="id" value="@entity.Id" />
                            <a href="#" onclick="document.getElementById('form-@entity.Id').submit();">Удалить</a>
                        </form>

                    </div>
                }
            </div>
        }
    </div>
    <div>
        <h3>Добавки</h3>
        <div class="div-box">
            <a asp-area="" asp-controller="Admin" asp-action="ToppingsEdit" asp-route-id="">Добавить Добавки</a>
        </div>
        @if (toppings.Any())
        {
            <div>
                @foreach (var entity in toppings)
                {
                    <div>
                        <span>
                            @($"{entity.Name}")
                        </span>
                        |
                        <a asp-area="" asp-controller="Admin" asp-action="ToppingsEdit" asp-route-id="@entity.Id">Редактировать</a>
                        |
                        <form style="display: inline-block;" id="form-category-@entity.Id" asp-area=""
                              asp-controller="Admin" asp-action="ToppingsDelete" method="post">
                            <input type="hidden" name="id" value="@entity.Id" />
                            <a href="#" onclick="document.getElementById('form-category-@entity.Id').submit();">Удалить</a>
                        </form>

                    </div>
                }
            </div>
        }
    </div>
    
    <div class="div-box">
        <form asp-area="" asp-controller="Account" asp-action="Logout" method="post">
            <input type="submit" value="Выйти"/>
        </form>
    </div>
</div>

RestarauntWebApp/Views/Admin/ServiceCategoriesEdit.cshtml
@model ServiceCategory
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<div>
    <h2>
        @strTitle
    </h2>
    <div>
        <form asp-area="" asp-controller="Admin" asp-action="ServiceCategoriesEdit" method="post">
            <input type="hidden" asp-for="Id"/>
            <input type="hidden" asp-for="DateCreated"/>
            
            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title"/>
                <span asp-validation-for="Title"></span>
            </div>
            
            <input type="submit" value="Сохранить"/>
        </form>
    </div>
</div>

RestarauntWebApp/Views/Admin/ServicesEdit.cshtml
@model Service
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<style>
    button{
        color: #000 !important;
    }
</style>

<script src="https://cdn.tiny.cloud/1/mb85kxtsc4oiknkstnihv9iqf01r1cw1d0w597fvsj47bk6a/tinymce/8/tinymce.min.js" referrerpolicy="origin" crossorigin="anonymous"></script>

<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="" asp-controller="Admin" asp-action="ServicesEdit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id"/>
            <input type="hidden" asp-for="DateCreated"/>
            <input type="hidden" asp-for="Photo"/>
            
            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <select asp-for="ServiceCategoryId">
                    <option value="">Выберите из списка...</option>
                    @foreach (ServiceCategory entity in ViewBag.ServiceCategories)
                    {
                        <option value="@entity.Id">@entity.Title</option>
                    }
                </select>
                <span asp-validation-for="ServiceCategoryId"></span>
            </div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title"/>
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Type"></label>
                <select asp-for="Type" asp-items="Html.GetEnumSelectList<ServiceTypeEnum>()"></select>
                <span asp-validation-for="Type"></span>
            </div>
            <div class="div-box">
                <label asp-for="DescriptionShort"></label>
                <input asp-for="DescriptionShort" />
                <span asp-validation-for="DescriptionShort"></span>
            </div>
            <div class="div-box">
                <label asp-for="Description"></label>
                <textarea asp-for="Description"></textarea>
                <span asp-validation-for="Description"></span>
            </div>
            <div class="div-box">
                <label asp-for="Photo"></label>
                <input type="file" name="titleImageFile" id="titleImageFile"/>
                <div>
                    <img class="img-block" src="~/img/@Model.Photo"/>
                </div>
            </div>
            <input type="submit" value="Сохранить"/>
        </form>
    </div>
</div>
<script>
    tinymce.init({
      selector: 'textarea',
      language: 'ru',
      onboarding: false,
      plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount',
      toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link media table mergetags | addcomment showcomments | spellcheckdialog a11ycheck typography uploadcare | align lineheight | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
      automatic_uploads: true,
      images_upload_url: '/admin/SaveEditorImg',
      images_reuse_filename: false,
      image_dimensions: false,
      paste_data_images: true,
      convert_urls: false
    });
</script>

RestarauntWebApp/Views/Admin/ToppingsEdit.cshtml
@model Topping
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<div>
    <h2>
        @strTitle
    </h2>
    <div>
        <form asp-area="" asp-controller="Admin" asp-action="ToppingsEdit" method="post">
            <input type="hidden" asp-for="Id" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Name"></label>
                <input asp-for="Name" />
                <span asp-validation-for="Name"></span>
            </div>
            <div class="div-box">
                <label asp-for="Price"></label>
                <input asp-for="Price" />
                <span asp-validation-for="Price"></span>
            </div>

            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>

RestarauntWebApp/Views/Dishes/Index.cshtml
@model IEnumerable<DishDTO>
@{
    string strTitle = "Меню";
    ViewBag.Title = strTitle;
}

@await Html.PartialAsync("_SidebarPartial")
<div class="col-8 col-12-medium imp-medium">
    <div id="content">
        @if (Model.Any())
        {
            <section class="box article-list">
                <h2 class="icon fa-file-alt">
                    @strTitle
                </h2>
                @foreach (var entity in Model)
                {
                    <article class="box excerpt">
                        <a asp-area="" asp-controller="Dishes" asp-action="Show" asp-route-id="@entity.Id" class="image left image-dish-list">
                            <img src="~/img/@entity.PhotoFileName" alt=""/>
                        </a>
                        <div>
                            <header>
                                <h3>
                                    <a asp-area="" asp-controller="Dishes" asp-action="Show" asp-route-id="@entity.Id">
                                        @entity.Name
                                    </a>
                                </h3>
                            </header>
                            <p>
                                Цена: @entity.Price р.
                            </p>
                            <p>
                                Вес: @entity.Weight г.
                            </p>
                            <p>
                                @Html.Raw(entity.Description)
                            </p>
                        </div>
                    </article>
                }
            </section>
        }
    </div>
</div>

RestarauntWebApp/Views/Dishes/Show.cshtml
@model DishDTO
@{
    string? strTitle = Model.Name;
    ViewBag.Title = strTitle;
}
@await Html.PartialAsync("_SidebarPartial")
<div class="col-8 col-12-medium imp-medium">
    <div id="content">
        <h2 class="dish-item">
            @strTitle
        </h2>
        @if (Model.CategoryName != null)
        {
            <div class="dish-item">
                Категория: <span class="text-bold">@Model.CategoryName</span>
            </div>
        }
        <div class="dish-item">
            Цена: @Model.Price р.
        </div>
        <div class="dish-item">
            Вес: @Model.Weight г.
        </div>
        <div class="dish-item">
           <img src="~/img/@Model.PhotoFileName" class="img-block"/>
        </div>
        <div class="dish-item">
            @Html.Raw(Model.Description)
        </div>
        @if (Model.ToppingsDTO != null && Model.ToppingsDTO.Any())
        {
            <p>Можно добавить:</p>
            <div class="dish-item">
            @foreach (var toppings in Model.ToppingsDTO)
            {
                <div class="dish-item">
                    <div>@toppings.Name: @toppings.Price р.</div>
                </div>
            }
            </div>
        }
    </div>
</div>

RestarauntWebApp/Views/Home/Contacts.cshtml
@inject IConfiguration config
@{
    AppConfig? appConfig = config.GetSection("Project").Get<AppConfig>();
    string strTitle = "Контакты";
    ViewBag.Title = strTitle;
}
@await Html.PartialAsync("_SidebarPartial")
<div class="col-8 col-12-medium imp-medium">
    <div id="content">
        <article>
            <header class="major">
                <h2>@strTitle</h2>
            </header>
            <div>
                Телефон: <span class="text-bold"><a href="tel:@appConfig?.Company.PhoneShort">@appConfig?.Company.PhoneShort</a></span>
            </div>
            <div>
                Email: <span class="text-bold"><a href="mailto:@appConfig?.Company.Email">@appConfig?.Company.Email</a></span>
            </div>
        </article>
    </div>
</div>

RestarauntWebApp/Views/Home/Index.cshtml
@await Html.PartialAsync("_SidebarPartial")
<div class="col-8 col-12-medium imp-medium">
	<div id="content">
		<article>
			<header class="major">
				<h2>Добро пожаловать на сайт</h2>
				<p>Лозунг</p>
			</header>
			<span class="image featured"><img src="img/pic08.jpg" alt="welcome"/></span>
		</article>

	</div>
</div>

RestarauntWebApp/Views/Services/Index.cshtml
@model IEnumerable<ServiceDTO>
@{
    string strTitle = "Услуги";
    ViewBag.Title = strTitle;
}

@await Html.PartialAsync("_SidebarPartial")
<div class="col-8 col-12-medium imp-medium">
    <div id="content">
        @if (Model.Any())
        {
            <section class="box article-list">
                <h2 class="icon fa-file-alt">
                    @strTitle
                </h2>
                @foreach (var entity in Model)
                {
                    <article class="box excerpt">
                        <a asp-area="" asp-controller="Services" asp-action="Show" asp-route-id="@entity.Id" class="image left image-service-list">
                            <img src="~/img/@entity.PhotoFileName" alt=""/>
                        </a>
                        <div>
                            <header>
                                <h3>
                                    <a asp-area="" asp-controller="Services" asp-action="Show" asp-route-id="@entity.Id">
                                        @entity.Title
                                    </a>
                                </h3>
                            </header>
                            @if (entity.CategoryName != null)
                            {
                                <div>
                                    Категория: <span class="text-bold">@entity.CategoryName</span>
                                </div>
                            }
                            <p>
                                @entity.DescriptionShort
                            </p>
                        </div>
                    </article>
                }
            </section>
        }
    </div>
</div>

RestarauntWebApp/Views/Shared/Components/Menu/Default.cshtml
<nav id="nav">
    <ul>
        <li>
            <a asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
        </li>
        <li>
            <a asp-area="" asp-controller="Dishes" asp-action="Index">Меню</a>
        </li>
        <li>
            <a asp-area="" asp-controller="Home" asp-action="Contacts">Контакты</a>
        </li>
    </ul>
</nav>

RestarauntWebApp/Views/Shared/_CssPartial.cshtml
<link rel="stylesheet" href="~/css/main.min.css" />

RestarauntWebApp/Views/Shared/_FooterPartial.cshtml
@inject IConfiguration config
@{
    AppConfig? appConfig = config.GetSection("Project").Get<AppConfig>();
}

<!-- Footer Wrapper -->
<div id="footer-wrapper">
	<footer id="footer" class="container">
		<div class="row">
			<div class="col-12">
				<div id="copyright">
					<ul class="menu">
						<li>&copy; @appConfig?.Company.Name. All rights reserved</li>
						<li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
					</ul>
				</div>
			</div>
		</div>
	</footer>
</div>

RestarauntWebApp/Views/Shared/_HeaderPartial.cshtml
@inject IConfiguration config
@{
    AppConfig? appConfig = config.GetSection("Project").Get<AppConfig>();
}

<!-- Header Wrapper -->
<div id="header-wrapper">
    <div class="container">

        <!-- Header -->
        <header id="header">
            <div class="inner">

                <!-- Logo -->
                <h1>
                    <a asp-area="" asp-controller="Home" asp-action="Index" id="logo">
                        @appConfig?.Company.Name
                    </a>
                </h1>
                @(await Html.PartialAsync("Components/Menu/Default"))
            </div>
        </header>

    </div>
</div>

RestarauntWebApp/Views/Shared/_HeaderPartical.cshtml
@inject IConfiguration config
@{
    AppConfig? appConfig = config.GetSection("Project").Get<AppConfig>();
}

<!-- Header Wrapper -->
<div id="header-wrapper">
    <div class="container">

        <!-- Header -->
        <header id="header">
            <div class="inner">

                <!-- Logo -->
                <h1>
                    <a asp-area="" asp-controller="Home" asp-action="Index" id="logo">
                        @appConfig?.Company.Name
                    </a>
                </h1>
                @(await Component.InvokeAsync<MenuViewComponent>())
            </div>
        </header>

    </div>
</div>

RestarauntWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
	@await Html.PartialAsync("_MetaPartial")
   	@await Html.PartialAsync("_CssPartial")
</head>
<body class="left-sidebar is-preload">
	<div id="page-wrapper">
		@await Html.PartialAsync("_HeaderPartial")
		<div id="main-wrapper">
			<div class="wrapper style2">
				<div class="inner">
					<div class="container">
						<div class="row">
							@RenderBody()
						</div>
					</div>
				</div>
			</div>
		</div>
		@await Html.PartialAsync("_FooterPartial")
	</div>
	@await Html.PartialAsync("_ScriptsPartial")
</body>
</html>

RestarauntWebApp/Views/Shared/_MetaPartial.cshtml
@inject IConfiguration config
@{
    AppConfig? appConfig = config.GetSection("Project").Get<AppConfig>();
}
<title>@(ViewBag.Title ?? appConfig?.Company.Name)</title>
<link rel="shortcut icon" href="img/pic01.jpg"/>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />

RestarauntWebApp/Views/Shared/_ScriptsPartial.cshtml
<script src="~/js/scripts.min.js" asp-append-version="true"></script>

RestarauntWebApp/Views/Shared/_SidebarPartial.cshtml
<div class="col-4 col-12-medium">
    <div id="sidebar">
        <section>
            <header class="major">
                <h2>Добро пожаловать!</h2>
            </header>
            <p>
                Приветственное сообщение.
            </p>
            <footer>
                <a asp-area="" asp-controller="Dishes" asp-action="Index" class="button icon solid fa-info-circle">
                    Перейти к услугам
                </a>
            </footer>
        </section>
    </div>
</div>